# Perzeptron
Deep Learning - KI29  
Deggendorf Institute of Technology  
Prof. Dr. Florian Wahl

## Teil 1: Perzeptron Beispiel ohne numpy
1. Machen Sie sich mit Jupyter Notebooks vertraut
2. Implementieren Sie ein Hello World
3. Legen Sie die Listen `inputs`, `weights` mit je 4 Elementen (4 Eingänge, 1 Neuron) an, sowie die Variable `bias` an
4. Berechnen Sie den Output (ohne Aktivierungsfunktion) "händisch", ohne Schleifen

In [31]:
print("Hello World!")

Hello World!


In [32]:
inputs = [.1, .2, .3, .4]

weights = [1, 0, -.5, .2]

bias = .3

output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias

print(output)

0.33


## Teil 2: Mehr Perzeptronen
Erweitern Sie Ihr Beispiel um 2 weitere Perzeptronen.

In [33]:
inputs = [.1, .2, .3, .4]

weights1 = [1, 0, -.5, .2]
weights2 = [1, -.5, .2, 0]
weights3 = [.2, 1, -.5, 0]

bias1 = .3
bias2 = .1
bias3 = -.5

output1 = inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1
output2 = inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2
output3 = inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3

print([output1, output2, output3])

[0.33, 0.16, -0.42999999999999994]


## Teil 3: Perzeptron Beispiel mit numpy
1. Machen Sie sich mit numpy arrays vertraut
2. Implementieren Sie das Beispiel aus Teil 1.4, aber dieses Mal mit numpy und der Funktion `np.dot()`
3. Implementieren Sie das Beispiel aus Teil 2, aber dieses Mal mit numpy und der Funktion `np.dot()`

In [34]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [35]:
import numpy as np

In [36]:
np_inputs = np.array(inputs)

np_weights = np.array(weights)

output = np.dot(np_inputs, np_weights) + bias

print(output)

0.33


In [37]:
np_inputs = np.array(inputs)

np_weights1 = np.array(weights1)
np_weights2 = np.array(weights2)
np_weights3 = np.array(weights3)

output1 = np.dot(np_inputs, np_weights1) + bias1
output2 = np.dot(np_inputs, np_weights2) + bias2
output3 = np.dot(np_inputs, np_weights3) + bias3

print([output1, output2, output3])

[np.float64(0.33), np.float64(0.16), np.float64(-0.42999999999999994)]


In [41]:
np_inputs = np.array(inputs)

np_weights = np.array([
    weights1,
    weights2,
    weights3
])

np_biases = np.array([bias1, bias2, bias3])

output = np.dot(np_weights, np_inputs) + np_biases

print(output)

[ 0.33  0.16 -0.43]


## Teil 4: Mehrere Observationen
Skalieren Sie das Beispiel so, dass es für mehrere Observationen (hier 3) und Perzeptronen (hier 3) in einer Schicht funktioniert. Legen Sie hierfür die 4x3 Matritzen für `inputs` und `weights` als Listen von Listen an.

In [42]:
np_inputs = np.array([
    [.1, .2, .3, .4],
    [.3, .1, .2, .4],
    [.1, .2, .4, .3]
])

np_weights = np.array([
    [1, 0, -.5, .2],
    [1, -.5, .2, 0],
    [.2, 1, -.5, 0]
])

np_biases = np.array([.3, .1, -.5])

outputs = np.dot(np_inputs, np_weights.T) + np_biases

print(outputs)

[[ 0.33  0.16 -0.43]
 [ 0.58  0.39 -0.44]
 [ 0.26  0.18 -0.48]]
